import { Target, Award, CheckCircle2, HelpCircle, BookOpen, Video, Link as LinkIcon, Bell } from 'lucide-react';

export const MOCK_FEED_ITEMS = [
  {
    id: "1",
    type: "Announcement",
    user: { name: "Maurice E.", initial: "M", role: "Instructor" },
    time: "2 hours ago",
    title: "Faculty Note: Sprint 3 Deliverables",
    content: "A quick reminder that the 'Hooking up Authentication Flows' deliverable is due tomorrow. Office hours are tonight at 8 PM EST. Please make sure your Supabase env variables are correctly formatted.",
    iconName: "Bell",
    color: "text-rose-500",
    bg: "bg-rose-500/10",
    endorsements: 24,
    hasEndorsed: false,
    repliesCount: 4,
    sprintContext: "Sprint 3"
  },
  {
    id: "2",
    type: "Submission",
    user: { name: "Sarah J.", initial: "S", role: "Student" },
    time: "4 hours ago",
    title: "Deliverable: Implementing OAuth Providers",
    content: "Just submitted my sprint deliverable. The GitHub integration took some troubleshooting but the Supabase docs were super helpful. Anyone else running into localhost redirect loops?",
    iconName: "CheckCircle2",
    color: "text-emerald-500",
    bg: "bg-emerald-500/10",
    endorsements: 12,
    hasEndorsed: true,
    repliesCount: 3,
    sprintContext: "Sprint 3"
  },
  {
    id: "3",
    type: "Question",
    user: { name: "Marcus T.", initial: "M", role: "Student" },
    time: "1 day ago",
    title: "Supabase Row Level Security (RLS) policies giving 403s",
    content: "Has anyone run into an issue where standard authenticated users are getting 403 Forbidden errors when trying to read from the public.profiles table? I set up the policies according to the sprint guide.",
    iconName: "HelpCircle",
    color: "text-blue-500",
    bg: "bg-blue-500/10",
    endorsements: 8,
    hasEndorsed: false,
    repliesCount: 6,
    sprintContext: "Sprint 3"
  },
  {
    id: "5",
    type: "Peer Review",
    user: { name: "Elena R.", initial: "E", role: "Premium" },
    time: "2 days ago",
    title: "Review Request: OAuth Edge Function Logic",
    content: "Before I submit my final deliverable, could someone peer review my token handling logic in the Edge function? I want to ensure my redirect latency is optimized.",
    iconName: "BookOpen",
    color: "text-purple-500",
    bg: "bg-purple-500/10",
    endorsements: 5,
    hasEndorsed: false,
    repliesCount: 1,
    sprintContext: "Sprint 3"
  },
  {
    id: "6",
    type: "Resource",
    user: { name: "David M.", initial: "D", role: "Student" },
    time: "2 days ago",
    title: "Guide: Vercel AI SDK vs LangChain",
    content: "Found this incredible deep-dive article comparing the Vercel AI SDK to LangChain for building streaming RAG apps. Might be useful for next week's Capstone project planning!",
    iconName: "LinkIcon",
    color: "text-[#9CA3AF]",
    bg: "bg-white/5",
    endorsements: 32,
    hasEndorsed: false,
    repliesCount: 2,
    sprintContext: "General"
  },
  {
    id: "7",
    type: "Win",
    user: { name: "James L.", initial: "J", role: "Premium" },
    time: "3 days ago",
    title: "Mastered: Academic OS Dashboard V1",
    content: "Finally shipped the dashboard logic! The Framer Motion animations took a lot of finessing, but the UI is feeling incredibly smooth.",
    iconName: "Award",
    color: "text-[#B08D57]",
    bg: "bg-[#B08D57]/10",
    endorsements: 56,
    hasEndorsed: false,
    repliesCount: 8,
    sprintContext: "Sprint 2"
  }
];
